import Api from '@/api/index';
export default {
  columns: [
    {
      name: '基本信息',
      classList: 'form-basic-group',
      renderType: 'form',
      items: [
        {
          prop: 'billNo',
          type: 'input',
          label: '单据编号',
          props: {
            placeholder: '单据编号',
            disabled: true,
          },
        },
        {
          prop: 'documentStatus',
          type: 'input',
          label: '单据状态',
          props: {
            placeholder: '单据状态',
            disabled: true,
          },
        },
        {
          prop: 'billName',
          type: 'input',
          label: '单据类型',
          props: {
            placeholder: '单据类型',
            disabled: true,
          },
        },
        {
          prop: 'date',
          type: 'date',
          label: '日期',
          props: {
            format: 'YYYY-MM-DD',
            valueFormat: 'YYYY-MM-DD',
            placeholder: '请选择日期',
            disabled: true,
          },
        },
        {
          prop: 'operatName',
          type: 'input',
          label: '运营跟单',
          props: {
            placeholder: '运营跟单',
            disabled: true,
          },
        },
        {
          prop: 'orgName',
          type: 'input',
          label: '组织名称',
          props: {
            placeholder: '组织名称',
            disabled: true,
          },
        },
      ],
    },
    {
      name: '明细信息',
      classList: 'form-detail-group',
      renderType: 'table',
      prop: 'executePricingItemList',
      items: [
        // {
        //   type: 'selection',
        //   fixed: 'left',
        //   width: '55',
        //   showFunc(detailData) {
        //     return ['1876789752111362049', '1876789881673412609'].includes(
        //       detailData?.dcErpOrderStatus
        //     );
        //   },
        // },

        {
          prop: 'qty',
          minWidth: '100px',
          type: 'common',
          is: 'el-input-number',
          props: {
            min: 0,
            controls: false,
            precision: 2,
            placeholder: '请输入数量',
            disabled: true,
          },
          label: '数量',
        },
        {
          prop: 'unitName',
          minWidth: '100px',
          // type: 'common',
          // is: 'el-input',
          label: '单位',
          type: 'dict',
          dictKey: '计量单位',
          labelKey: 'bizValue',
          valueKey: 'bizValue',
          props: {
            disabled: true,
          },
        },
        {
          prop: 'materialNumber',
          minWidth: '120px',
          label: '物料编码',
          minWidth: '140px',
          type: 'remote-select',
          props: {
            disabled: true,
            renderLabel(op, labelKey) {
              return `${op[labelKey]}(${op.fname})`;
            },
            queryKey: 'number',
            labelKey: 'fnumber',
            valueKey: 'fnumber',
            action: Api.pdp.execution.materials,
          },
        },
        {
          prop: 'materialName',
          minWidth: '220px',
          type: 'common',
          is: 'el-input',
          props: {
            placeholder: '选择物料编码自动生成',
            disabled: true,
          },
          label: '物料名称',
        },
        {
          prop: 'specification',
          minWidth: '220px',
          type: 'common',
          is: 'el-input',
          props: {
            placeholder: '选择物料编码自动生成',
            disabled: true,
          },
          label: '规格型号',
        },
        // {
        //   prop: 'type',
        //   label: '源单类型',
        //   minWidth: '200px',
        //   type: 'common',
        //   is: 'el-input',
        //   props: {
        //     disabled: true,
        //     placeholder: '源单类型',
        //   },
        // },
        {
          prop: 'noStandardCost',
          minWidth: '100px',
          type: 'common',
          is: 'el-input-number',
          fixed: 'left',
          required: true,
          props: {
            min: 0,
            controls: false,
            precision: 2,
            placeholder: '请输入',
          },
          label: '非标件成本',
        },
        // {
        //   prop: 'materialCost',
        //   minWidth: '100px',
        //   type: 'common',
        //   is: 'el-input-number',
        //   fixed: 'left',
        //   required: true,
        //   props: {
        //     min: 0,
        //     controls: false,
        //     precision: 2,
        //     placeholder: '请输入',
        //   },
        //   label: '物料成本',
        // },
        // {
        //   prop: 'lbuHumanDay',
        //   minWidth: '100px',
        //   type: 'common',
        //   is: 'el-input-number',
        //   fixed: 'left',
        //   required: true,
        //   props: {
        //     min: 0,
        //     controls: false,
        //     precision: 2,
        //     placeholder: '请输入',
        //   },
        //   label: 'LBU人天',
        // },
        {
          prop: 'standardCost',
          minWidth: '100px',
          type: 'common',
          is: 'el-input-number',
          fixed: 'left',
          required: true,
          props: {
            min: 0,
            controls: false,
            precision: 2,
            placeholder: '请输入',
          },
          label: '标准间成本',
        },
        {
          prop: 'factoryLaborCost',
          minWidth: '100px',
          type: 'common',
          is: 'el-input-number',
          fixed: 'left',
          required: true,
          props: {
            min: 0,
            controls: false,
            precision: 2,
            placeholder: '请输入',
          },
          label: '厂内人力费用',
        },
        // {
        //   prop: 'lbuCost',
        //   minWidth: '100px',
        //   type: 'common',
        //   is: 'el-input-number',
        //   fixed: 'left',
        //   required: true,
        //   props: {
        //     min: 0,
        //     controls: false,
        //     precision: 2,
        //     placeholder: '请输入',
        //   },
        //   label: 'LBU成本',
        // },
        // {
        //   prop: 'ossHumanDay',
        //   minWidth: '100px',
        //   type: 'common',
        //   is: 'el-input-number',
        //   fixed: 'left',
        //   required: true,
        //   props: {
        //     controls: false,
        //     min: 0,
        //     precision: 2,
        //     placeholder: '请输入',
        //   },
        //   label: 'OSS人天',
        // },
        {
          prop: 'wiringCost',
          minWidth: '100px',
          type: 'common',
          is: 'el-input-number',
          fixed: 'left',
          required: true,
          props: {
            controls: false,
            min: 0,
            precision: 2,
            placeholder: '请输入',
          },
          label: '架线费用',
        },
        // {
        //   prop: 'ossCost',
        //   minWidth: '100px',
        //   type: 'common',
        //   is: 'el-input-number',
        //   fixed: 'left',
        //   required: true,
        //   props: {
        //     min: 0,
        //     controls: false,
        //     precision: 2,
        //     placeholder: '请输入',
        //   },
        //   label: 'OSS成本',
        // },
        {
          prop: 'lineCost',
          minWidth: '100px',
          type: 'common',
          is: 'el-input-number',
          fixed: 'left',
          required: true,
          props: {
            min: 0,
            controls: false,
            precision: 2,
            placeholder: '请输入',
          },
          label: '守线费用',
        },
        {
          prop: 'mtoNo',
          minWidth: '120px',
          type: 'common',
          is: 'el-input',
          label: '专案号',
          props: {
            disabled: true,
            placeholder: '系统生成',
          },
        },
      ],
    },
  ],
};
