export const data = {
  projectId: '1928370358690758657',
  funcFieldTemplateId: {
    configName: '交付启动会人员配置',
    configCode: 'DELIVERED',
    updateUser: '1844536206996885515',
    updateTime: '2025-07-15 18:27:51',
    createDept: '1788409957593038850',
    isDeleted: 0,
    requiredField:
      'DC_PMS_PROJECT_ROLE_BDDRI,DC_PMS_PROJECT_ROLE_TPMDRI,DC_PMS_PROJECT_ROLE_GD,DC_PMS_PROJECT_ROLE_OPMDRI,DC_PMS_PROJECT_ROLE_PC,DC_PMS_PROJECT_ROLE_JGDRI',
    createTime: '2025-05-29 16:15:46',
    bindField:
      'DC_PMS_PROJECT_ROLE_JGDRI,DC_PMS_PROJECT_ROLE_DQDRI,DC_PMS_PROJECT_ROLE_RJDRI,DC_PMS_PROJECT_ROLE_BDDRI,DC_PMS_PROJECT_ROLE_TPMDRI,DC_PMS_PROJECT_ROLE_SJDRI,DC_PMS_PROJECT_ROLE_PQEDRI,DC_PMS_PROJECT_ROLE_IPQCDRI,DC_PMS_PROJECT_ROLE_FAEDRI,DC_PMS_PROJECT_ROLE_OPMDRI,DC_PMS_PROJECT_ROLE_PC,DC_PMS_PROJECT_ROLE_JGZZ,DC_PMS_PROJECT_ROLE_DQZZ,DC_PMS_PROJECT_ROLE_XC,DC_PMS_PROJECT_ROLE_PQA,DC_PMS_PROJECT_ROLE_PMC,DC_PMS_PROJECT_ROLE_GD',
    tenantId: '000000',
    createUser: '1844536206996885508',
    id: '1928002308711813122',
    status: 1,
    isInfo: true,
  },
  dcPdpFuncFieldList: [
    {
      label: '机构DRI',
      filedKey: 'DC_PMS_PROJECT_ROLE_JGDRI',
      bindUserIds: '1921734641514692641',
      requiredField: true,
    },
    {
      label: '电气DRI',
      filedKey: 'DC_PMS_PROJECT_ROLE_DQDRI',
      bindUserIds: '',
      requiredField: false,
    },
    {
      label: '软件DRI',
      filedKey: 'DC_PMS_PROJECT_ROLE_RJDRI',
      bindUserIds: '',
      requiredField: false,
    },
    {
      label: 'BDDRI',
      filedKey: 'DC_PMS_PROJECT_ROLE_BDDRI',
      bindUserIds: '1921734641514692641',
      requiredField: true,
    },
    {
      label: 'TPMDRI',
      filedKey: 'DC_PMS_PROJECT_ROLE_TPMDRI',
      bindUserIds: '1921734641514692641',
      requiredField: true,
    },
    {
      label: '视觉DRI',
      filedKey: 'DC_PMS_PROJECT_ROLE_SJDRI',
      bindUserIds: '',
      requiredField: false,
    },
    {
      label: 'PQEDRI',
      filedKey: 'DC_PMS_PROJECT_ROLE_PQEDRI',
      bindUserIds: '',
      requiredField: false,
    },
    {
      label: 'IPQCDRI',
      filedKey: 'DC_PMS_PROJECT_ROLE_IPQCDRI',
      bindUserIds: '',
      requiredField: false,
    },
    {
      label: 'FAEDRI',
      filedKey: 'DC_PMS_PROJECT_ROLE_FAEDRI',
      bindUserIds: '',
      requiredField: false,
    },
    {
      label: 'OPMDRI',
      filedKey: 'DC_PMS_PROJECT_ROLE_OPMDRI',
      bindUserIds: '1921734641514692641',
      requiredField: true,
    },
    {
      label: 'PC',
      filedKey: 'DC_PMS_PROJECT_ROLE_PC',
      bindUserIds: '1921734641514692641',
      requiredField: true,
    },
    {
      label: '机构组装',
      filedKey: 'DC_PMS_PROJECT_ROLE_JGZZ',
      bindUserIds: '',
      requiredField: false,
    },
    {
      label: '电气组装',
      filedKey: 'DC_PMS_PROJECT_ROLE_DQZZ',
      bindUserIds: '',
      requiredField: false,
    },
    { label: '线材', filedKey: 'DC_PMS_PROJECT_ROLE_XC', bindUserIds: '', requiredField: false },
    { label: 'PQA', filedKey: 'DC_PMS_PROJECT_ROLE_PQA', bindUserIds: '', requiredField: false },
    { label: 'PMC', filedKey: 'DC_PMS_PROJECT_ROLE_PMC', bindUserIds: '', requiredField: false },
    {
      label: '运营跟单',
      filedKey: 'DC_PMS_PROJECT_ROLE_GD',
      bindUserIds: '1921734641514692641',
      requiredField: true,
    },
  ],
  completeSetDate: '2025-07-16',
  etd: '2025-07-24',
  'lastest ETD': '2025-07-31',
  isClearance: true,
  keySop: true,
  needEsd: true,
  needCrw: true,
  needEsdPipe: true,
  mtoNo: 'DC25070533',
  number: '100103010-252191A',
  name: 'BTB链路测试治具',
};
