export default {
  columns: [
    {
      name: '基本信息',
      items: [
        { prop: 'projectName', type: 'string', description: '项目名称' },
        { prop: 'projectNumber', type: 'string', description: '项目编号' },
        { prop: 'billTypeName', type: 'string', description: '单据类型' },
        { prop: 'billNumber', type: 'string', description: '单据编号' },
        { prop: 'orderDate', type: 'string', description: '下单日期' },
        { prop: 'customerName', type: 'string', description: '客户' },
        { prop: 'endCustomerName', type: 'string', description: '终端客户' },
        { prop: 'tpmName', type: 'string', description: 'TPM' },
        { prop: 'projectTypeName', type: 'string', description: '项目类型' },
        { prop: 'orderTypeName', type: 'string', description: '订单类型' },
        { prop: 'operationName', type: 'string', description: '运营跟单' },
        { prop: 'note', type: 'string', description: '备注' },
      ],
    },
    {
      name: '明细信息',
      items: [
        { prop: 'materialName', type: 'string', description: '物料名称' },
        { prop: 'materialNumber', type: 'string', description: '物料编码' },
        { prop: 'version', type: 'string', description: '版本号' },
        { prop: 'number', type: 'integer', description: '数量' },
        { prop: 'unitName', type: 'string', description: '单位' },
        { prop: 'bdName', type: 'string', description: 'BD(业务)' },
        { prop: 'contactPersonName', type: 'string', description: '联系人' },
        { prop: 'insidePmName', type: 'string', description: '内部PM' },
        { prop: 'institutionsName', type: 'string', description: '机构工程' },
        { prop: 'electronName', type: 'string', description: '电子工程' },
        { prop: 'softwareName', type: 'string', description: '软件工程' },
        { prop: 'electricalName', type: 'string', description: '电气工程' },
        { prop: 'phaseName', type: 'string', description: '阶段' },
        { prop: 'deviceAttributeName', type: 'string', description: '设备属性' },
        { prop: 'customerProductName', type: 'string', description: '客户产品' },
        { prop: 'productSeriesName', type: 'string', description: '产品系列' },
        { prop: 'customerDeliveryDate', type: 'string', description: '客户交期' },
        { prop: 'receiveLocation', type: 'string', description: '收货地址' },
        { prop: 'freeReasonName', type: 'string', description: '免费原因' },
        { prop: 'costProjectNumber', type: 'string', description: '成本归属专案' },
        { prop: 'responsiblePersonName', type: 'string', description: '责任人' },
        { prop: 'deviceName', type: 'string', description: '设备名称' },
      ],
    },
  ],
};
